### ISSUE TITLE
Add PayTM payment option

### ISSUE THREAD

**Issue by anandwana001** [anandwana001/Tech-Jalsa#5]
participants can pay through paytm for events.

**Comment by ak5hit** [comment]
Can I work on this?

**Comment by anandwana001** [comment]
@permanent-bnsl Yeah sure. remember, anyone can pay for any event to one account, which is of event admin.

**Comment by ak5hit** [comment]
Can I work on this using Android Studio?

**Comment by anandwana001** [comment]
Yea, this is native android application.

**Comment by ak5hit** [comment]
When It's doing Gradle build it's giving an error:

Error:Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  C:\Users\Akshit Bansal\AndroidStudioProjects\Tech-Jalsa-master\app\src\debug\google-services.json
  C:\Users\Akshit Bansal\AndroidStudioProjects\Tech-Jalsa-master\app\google-services.json

**Comment by ak5hit** [comment]
And sir please give a little bit more description of the PayTM option.

**Comment by anandwana001** [comment]
You have to create one firebase project and put google-services.json in this project.
We are looking to implement Paytm- integrating paytm api to access account, profile in order to make transaction of money possible

**Comment by ak5hit** [comment]
That google-services.json should have which Google services?
Tracking Analytics?

**Comment by anandwana001** [comment]
We are using firebase in this application for firebase analytics and firebase notifications fcm.

**Comment by ak5hit** [comment]
Should I proceed with this
http://paywithpaytm.com/developer/paytm_api_doc?target=integration-guide

**Comment by anandwana001** [comment]
yes

**Comment by anandwana001** [comment]
@permanent-bnsl any update or problem you are facing?

**Comment by ak5hit** [comment]
No problem till now but it might take some time, as I'm new to this.

**Comment by ak5hit** [comment]
Can you give a little about the positioning of paytm option ?

**Comment by ak5hit** [comment]
The process is involving many authorisation type things, give some directions I'm not getting what to do ?

**Comment by anandwana001** [comment]
we have to close this issue as not required by core team. I will introduce another issue which involves paytm feature and you can continue on that.
