### ISSUE TITLE
Share App Feature

### ISSUE THREAD

**Issue by anandwana001** [anandwana001/Tech-Jalsa#7]
Implement share app feature, user can share over whats app, facebook and other social media.

**Comment by ak5hit** [comment]
Can I do this ?

**Comment by anandwana001** [comment]
Yes

**Comment by ak5hit** [comment]
This app is not live on Play Store than what URL will I give to users for sharing?

**Comment by anandwana001** [comment]
leave the url blank for now, just test with some fake url and make a PR. After publishing the app on play store we will fill the appropriate url.

**Comment by ak5hit** [comment]
Any suggestions for placing of share button?

**Comment by anandwana001** [comment]
overflow menu will be ok for now
